default world command-adapter {
    import http-incoming-handler: http.incoming-handler
    import http: http.types
    import fastly: fastly.fastly
    
    export run: func() -> result
}                
